#vim :
sudo: required
dist: trusty

language:
 - c
 - python

compiler:
  - gcc

env:
 matrix:
  - TEST=python-api TYPE=style
  - TEST=python-api TYPE=unittests
  - TEST=python-api TYPE=integration

  - TEST=server TYPE=style
  - TEST=server TYPE=unittests
  - TEST=server TYPE=integration

install:
 - chmod a+rx $PWD/.travis-*.sh
 - $PWD/.travis-setup.sh

script:
 - $PWD/.travis-run.sh

after_script:
 - $PWD/.travis-after.sh

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"
